# Generated by Django 4.2 on 2025-10-23 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='notified_to_expert',
            field=models.BooleanField(default=False),
        ),
    ]
