# Generated by Django 4.2 on 2025-11-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_notified_to_expert'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='return_status',
            field=models.CharField(choices=[('none', 'ثبت اولیه کاربر'), ('returned', 'برگشتی از کارشناس')], default='none', max_length=20),
        ),
    ]
