# Generated by Django 4.2 on 2025-11-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_filetransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تلفن اتاق'),
        ),
        migrations.AddField(
            model_name='user',
            name='room_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره اتاق'),
        ),
    ]
