# Generated by Django 4.2 on 2025-11-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_ticketmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
